//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupTable
    {
        public int PickupId { get; set; }
        public int PickupNo { get; set; }
        public string PickupName { get; set; }
        public Nullable<int> RouteId { get; set; }
    
        public virtual RoutesTable RoutesTable { get; set; }
    }
}
