//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutesTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoutesTable()
        {
            this.PickupTables = new HashSet<PickupTable>();
        }
    
        public int RouteId { get; set; }
        public string RouteName { get; set; }
        public int NoOfPickPoints { get; set; }
        public decimal Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickupTable> PickupTables { get; set; }
    }
}
